[network]
name = "simnet"

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"

[accounts.wallet_1]  
mnemonic = "sell invite acquire kitten bamboo drastic junk diesel output deliver sunny polygon quality effort win tennis dice claim side agent toward unfair subway uphold"

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital"

[accounts.wallet_3]
mnemonic = "board list obtain sugar hour worth raven scout denial thunder horse logic fury scorpion fold genuine phrase wealth news aim below celery when cabin"